grpc:
  client:
    student-grpc-service:
      address: static://localhost:5001
      negotiationType: plaintext
    teacher-grpc-service:
      address: static://localhost:5002
      negotiationType: plaintext